[tool.black]
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.ropeproject
  | \.tox
  | venv.*
  | _build
  | buck-out
  | build
  | dist
  | profiling
  | migrations
)/
'''

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
no_implicit_optional = true

[tool.pylint.messages_control]
disable = "C0103"
